version: '3.8'

services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db-container
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    networks:
      - postgres-network

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    volumes:
      - ./backend/user-service:/app
      - /app/libs # Exclude the jar directory from being overwritten
    ports:
      - "3000:8080"
    networks:
      - postgres-network
    depends_on:
      - postgres-db
    environment:
      SPRING_PROFILES_ACTIVE: dev2

  direct-message-service:
    build:
      context: ./backend/direct-message-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend/direct-message-service:/app
    networks:
      - postgres-network
    depends_on:
      - postgres-db

volumes:
  db_data:

networks:
  postgres-network:
    driver: bridge