name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v4'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/1052820698779/locations/global/workloadIdentityPools/k8s-pool/providers/k8s-provider'
          service_account: 'draftbash@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
      - uses: 'google-github-actions/setup-gcloud@v1'
      - name: Docker auth
        run: gcloud auth configure-docker
      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/draftbash-435005/draftbash-repo/draftbash-image:latest .
          docker push us-central1-docker.pkg.dev/draftbash-435005/draftbash-repo/draftbash-image:latest
        working-directory: ./nodeapp
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="prefix=k8s"
        working-directory: ./terraform
      - name: Terraform plan
        run: |
          terraform plan \
            -var="region=us-central1" \
            -var="project_id=$GCP_PROJECT_ID" \
            -var="container_image=us-central1-docker.pkg.dev/draftbash-435005/draftbash-repo/draftbash-image:latest" \
            -out=PLAN
        working-directory: ./terraform
      - name: Terraform apply
        run: terraform apply PLAN
        working-directory: ./terraform
            
            